POST http://localhost:3001/api/notes
Content-Type:  application/json

{
    "content": "VS code rest client is a pretty handle toollll",
    "important": true
}
###
GET http://localhost:3001/api/notes/